### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [nkonev/r2dbc-migrate-example#1]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by hantsy** [comment]
R2dbc is an alternative of JDBC.

Flyway/Liquibase for db migration using Jdbc, R2dbc Migrate just provides a solution for R2dbc instead of the existing Flyway/Liquibase.

**Comment by nkonev** [comment]
Thank you for your question.

My initial goal is "purity" - e. g. not to use JDBC (we know that Flyway is tied to JDBC) in case when I want to play with reactive paradigm. I found that there were no ready migration libraries for R2DBC, so I wrote my own.

As far as I've found in the [documentation](https://hibernate.org/reactive/documentation/1.0/reference/html_single/#_including_hibernate_reactive_in_your_project_build) of Hibernate Reactive - they use Vert.x-based drivers family to interact with database. I haven't test my library with it, I suppose my library won't work with Hibernate Reactive because I use Project Reactor's-based R2DBC drivers.
